---
compile_pdf:
  stage: build
  image: texlive/texlive
  script:
    - python compile.py
  artifacts:
    paths:
      - "**/*.pdf"
pages:
  stage: deploy
  script:
    - mkdir public
    - cp "**/*.pdf" public/
  artifacts:
    paths:
      - public
  only:
    - main
