---
compile_pdf:
  stage: build
  image: texlive/texlive
  script:
    - python compile.py
    - python generate_index_html.py
  artifacts:
    paths:
      - "**/*.pdf"
      - index.html
pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public
    - find . -name '*.pdf' -exec cp {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - main
