project:
  type: website

execute:
  freeze: auto

website:
  title: "MedTech Prototyping Skills"
  description: "Duke BME 254L - Spring 2026"
  site-url: "https://mlp6.github.io/MedTech-Prototyping-Skills/"
 
  repo-url: "https://github.com/mlp6/MedTech-Prototyping-Skills/"
  repo-actions: [issue]

  sidebar:
    background: "#2d63ba"
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 2
    contents:
      - section: "Course Information"
        contents:
        - href: course-syllabus.qmd
          text: Course Syllabus
        - href: https://canvas.duke.edu/courses/73999
          text: Canvas
        - href: https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=4d8bd7ca-c326-4c87-9e29-b3c9012f813e
          text: "Panopto Lecture Videos"
        - href: faq.qmd
          text: FAQ
      - section: "Learning Modules"
        contents:
        - href: lectures/medtech-skills-overview.qmd
          text: "MedTech Prototyping Skills Overview"
        - href: lectures/event-driven-state-machine.qmd
          text: "Event-Driven State Machines"
        - href: lectures/cad-onshape.qmd
          text: "CAD with Onshape"
        - href: lectures/git-fundamentals.qmd
          text: "Version Control (git)"
        - section: "EDA (KiCad)"
          contents:
          - href: lectures/EDA-KiCad-Schematic-Capture.qmd
            text: "Schematic Capture"
          - href: lectures/EDA-KiCad-SPICE.qmd
            text: "SPICE Modeling"
          - href: lectures/EDA-KiCad-PCB-Layout.qmd
            text: "PCB Layout"
        - href: lectures/c-programming.qmd
          text: "C Programming"
      - section: Labs
        contents:
        - href: labs/software-install-tutorials.qmd
          text: "Software Installation Tutorials"
        # - href: labs/event-driven-state-machine-lab.qmd
        - text: "Event-Driven State Machine (Kitchen Timer)"
        # - href: labs/hybrid_iii_6yo.qmd
        - text: "Hybrid III 6YO Head and Neck Lab"
        # - href: https://gitlab.oit.duke.edu/mlp6/kicad-spice
        - text: "KiCad & SPICE Lab (GitLab Repo)"
      - href: https://gitlab.oit.duke.edu/mlp6/lightbox
        text: "Lightbox (GitLab Repo)"
      - section: Resources
        contents:
        - href: https://sites.google.com/view/dukebmeindustryopportunities/home?authuser=0
          text: "BME in Industry"
        - href: resources/state_diagram.qmd
          text: "State Diagrams"
        - href: resources/bme-lab-policies.qmd
          text: "BME Lab Policies"
        - href: resources/3d_printing.qmd
          text: "3D Printing"
        - href: resources/git.qmd 
          text: "Git: Getting Started"
        - href: "kicad/"
          text: "Example KiCad Projects"

    page-footer:
      right: 'This page is built with [Quarto](https://quarto.org/).'
      left: "&copy; Copyright 2026, Mark Palmeri"

format:
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    linkcolor: "#5D737E"
  pdf:
    linkcolor: teal
toc: true
code-copy: hover
code-link: true
code-overflow: wrap
