---
title: "Firmware: Event-Driven State Machines"
date: "2026-01-06"
format:
  live-html: 
    output-file: arduino-state-machine-notes.html
  live-revealjs: 
    output-file: arduino-state-machine-slides.html
---

<!-- NOTE: this was originally in the first event-driven state machine lecture, but premature to present in lecture at the very beginning of the semester -->

## Kernel Events

- What is a "kernel"?
  - The part of the RTOS that interacts with hardware.
- Kernel events can be used to indicate that "something" has happened, which may dictate the function of the state machine.
  - Button press
  - Sensor crossing a threshold
  - Timer expiring
- When an event occurs, it triggers an **Interupt Service Routine** (`ISR`), which calls a **callback** function.

### Code: Switch-Case

- The simplest implementation of a state machine is a switch-case statement.
- The switch statement is used to select the current state.
- The case statements are used to implement the logic for each state.
  - Cases can be nested to implement sub-states.
  - Enumerations can be used to give states verbose names instead of numbers.
- The break statement is used to exit the switch statement.
- The default statement is used to handle unexpected states.

### Pseudo-Code

```C
enum device_states { init, run, sleep };

int device_state = init; // initialize state

/* structure to bookkeep state variables */
struct device_state_vars {
    int var1;
    int var2;
};

while (1) {
    switch (device_state) {
        case init:
            /* do stuff to initialize device */
            device_state = run; // change the state
            break;  // exit the switch statement
        case run:
            /* run device */
            if (condition) {
                device_state = sleep;
            }
            break;
        case sleep:
            /* sleep device */
            if (condition) {
                device_state = run;
            }
            break;
        default:
            /* handle unexpected state */
            break;
    }
}
```

The switch-case approach loses some of its elegance when there are many states and many transitions and states have entry / exit routines.

### Resources / Examples

- https://www.digikey.com/en/maker/tutorials/2023/how-to-program-an-arduino-finite-state-machine
- https://www.instructables.com/Finite-State-Machine-on-an-Arduino/