---
title: "MedTech Prototyping Skills: Software Installation & Tutorials"
date: "2026-08-24"
format:
  html: default
  pdf: default
---

## Git (Version Control)

Please follow the instructions on this dedicated [git page](../resources/git.qmd) to:

- Install `git`

- Configure `git`

- Setup an SSH key

- Provide links to `git` tutorials to reinforce the concepts and mechanics of
using `git`.

## KiCad (EDA)

- Please install KiCad (`v10.x`): [https://kicad.org](https://kicad.org)

::: callout-note
This installation file can be a bit large, so this may take a few minutes to
download.
:::

## Onshape (CAD)

- Please make sure to activate your invitation to Duke's Onshape server (see
email).

::: callout-note
If you did not receive an email invitation, please send Dr. Palmeri and your
TAs a private message on Ed.
:::

## Visual Studio Code (IDE)

We will be using [Visual Studio Code](https://code.visualstudio.com/) as the IDE
for all projects in this class.  In addition to installing the base program,
please install the following Extensions:

- PlantUML (generate state diagrams)

- GitLens (help with git operations / visualization)

- Microsoft C/C++ Extension Pack

- PlatformIO

- [GitHub CoPilot Chat](https://code.visualstudio.com/docs/copilot/overview) AI
coding assistant (optional, but highly recommended for inline autocompletion)

::: callout-tip
You can get "Pro" status for GitHub CoPilot by signing up for a free 
[GitHub Education Student](https://github.com/education/students) account.  
You will need a document to verify your student status that includes your dates
of enrollment, which your DukeCard does not contain.  Instead, you can get an
Enrollment Verification document through DukeHub (Academics Tab) and convert the
downloaded PDF to a JPG or PNG file to upload to GitHub.
:::

- `Codex` for agentic AI (you can enroll in ChatGPT EDU through Duke's [Software Manager](https://software-manager.oit.duke.edu/))

- Python & Jupyter extensions (for technical report preparation)

- [Conda](https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html) to install a Python virtual environment for Jupyter notebooks.

::: callout-note
You can use an existing Python installation on your laptop if you have one.
:::

## Arduino Nano Every

- Order yourself an [Arduino Nano Every](https://store-usa.arduino.cc/products/arduino-nano-every-with-headers?selectedStore=us).

::: callout-note
You do not have to order from the Arduino store if you can find this board
elsewhere, but please make sure you get the "Every" version of the Nano.  Other
versions of the board use different logic voltages and even different chips!
:::

- Make sure you have a data-cable USB cable to connect your Arduino Nano Every
to your laptop.

- Make sure that you have a USB memory key that can be used to download data from an oscillopscope (ours use an older USB-A connection, so make sure you have a USB-A port on your laptop or a USB-C to USB-A adapter).

## Technical Report Preparation

Each lab exercise will have an associated technical report submitted.  These
reports will be prepared and submitted using Python-based Jupyter notebooks that
will be included as part of your assignment git repositories.

You will need to be able to perform the following tasks in your Jupyter
notebooks:

- Read CSV text data saved from an oscilloscope.

- Perform simple statistics (e.g., mean, standard deviation, 95% CI) on the data.

- Generate plots

If you need to install a Python environment on your laptop, then this is a good starting point: [Getting Started with Python in VS Code](https://code.visualstudio.com/docs/python/python-tutorial).

This is a good tutorial on getting started with Jupyter notebooks in VS Code: [Jupyter Notebooks in Visual Studio Code](https://code.visualstudio.com/docs/python/jupyter-support).

## Lab Policies & Safety

Please review the [lab policies and safety guidelines](../resources/bme-lab-policies.qmd) for working in the lab.

## What to Submit

Complete the online Canvas "quiz" indicating completion of each of the main tasks above.
